### ISSUE TITLE
auth.json - password not being escaped properly

### ISSUE THREAD

**Issue by Gixxa** [DIGITALCRIMINAL/OnlyFans#1121]
So I tried using the email and password field but as soon as I use my password I get this error:

```
Traceback (most recent call last):
  File "D:\OnlyFans-master\start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "D:\OnlyFans-master\datascraper\main_datascraper.py", line 60, in start_datascraper
    api = main_helper.process_profiles(
  File "D:\OnlyFans-master\helpers\main_helper.py", line 598, in process_profiles
    temp_json_auth = ujson.load(
ValueError: Unrecognized escape sequence when decoding 'string'
```

My password uses chars such as %, ", ~ and others. I believe that the password is not being escaped properly.

**Comment by DIGITALCRIMINAL** [comment]
Latest commit should fix it

**Comment by Gixxa** [comment]
Sadly I can't confirm it. Still get exactly the same error message.

**Comment by DIGITALCRIMINAL** [comment]
Has this been fixed

**Comment by Gixxa** [comment]
@DIGITALCRIMINAL 

Sorry just saw your question now. No, it has not. This is the "new" error:

> Traceback (most recent call last):
>   File "D:\OnlyFans-master\start_ofd.py", line 44, in <module>
>     api = main_datascraper.start_datascraper(json_config, site_name_lower)
>   File "D:\OnlyFans-master\datascraper\main_datascraper.py", line 61, in start_datascraper
>     api = main_helper.process_profiles(
>   File "D:\OnlyFans-master\helpers\main_helper.py", line 610, in process_profiles
>     temp_json_auth = ujson.load(
> ValueError: Unrecognized escape sequence when decoding 'string'

**Comment by DIGITALCRIMINAL** [comment]
I need an example of a different password that causes the problem because it's working for me

**Comment by Gixxa** [comment]
@DIGITALCRIMINAL 

Ok, I changed my password and deleted all old sessions so I can share the old one. My old PW was:

3+&%gxm=RfmRZ-u,2$xn^Uk4!R\5G!uh.Q5tTZ:JR4@y87FG.~"p

With that it did not work. I left everything else (auth_id, sess, user_agent and x_bc) in the file and also deleted everything. It always showed the error I posted.

I now changed my password and it seems to work, at least I get further into the process. It now tells me "Access denied" 10 times and that I need to download geckodriver release 0.27.0 and put it under extras\OFLogin.  So I downloaded the 64 bit exe for Windows and put the .exe in said folder. After doing that I still gett "Access denied" 10 times followed by this:

> Opening Browser
> Traceback (most recent call last):
>   File "D:\OnlyFans-master\start_ofd.py", line 44, in <module>
>     api = main_datascraper.start_datascraper(json_config, site_name_lower)
>   File "D:\OnlyFans-master\datascraper\main_datascraper.py", line 81, in start_datascraper
>     setup, subscriptions = module.account_setup(
>   File "D:\OnlyFans-master\modules\onlyfans.py", line 127, in account_setup
>     cookies = oflogin.login(auth, domain, proxy)
>   File "D:\OnlyFans-master\extras\OFLogin\start_ofl.py", line 87, in login
>     email_input = web_browser.find_element_by_id("input-71")
>   File "C:\Users\Michael\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
>     return self.find_element(by=By.ID, value=id_)
>   File "C:\Users\Michael\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
>     return self.execute(Command.FIND_ELEMENT, {
>   File "C:\Users\Michael\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
>     self.error_handler.check_response(response)
>   File "C:\Users\Michael\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id="input-71"]

I believe that the escape error is fixed but I'll leave the post open for you to decide if you want to close it or keep it open until you check out the current traceback.

**Comment by DIGITALCRIMINAL** [comment]
> 3+&%gxm=RfmRZ-u,2$xn^Uk4!R\5G!uh.Q5tTZ:JR4@y87FG.~"p

Ahh I see, you can't have quotations or backward slashes in the JSON file

![image](https://user-images.githubusercontent.com/21285176/121182496-0bc57080-c85b-11eb-829d-c0d92c340368.png)

**Comment by Gixxa** [comment]
Initial issue has been solved --> closed.
