### ISSUE TITLE
Latest release will scrape , but wont download content

### ISSUE THREAD

**Issue by Daironman78** [DIGITALCRIMINAL/OnlyFans#1346]
I have downloaded the latest version of the Scraper, but it doesn't seem to be working properly for me so far. It will get to the point of showing you who your subbed to, You select who you want and then it will say that it is scraping then when it gets to the point of downloading it just sits there. I have tried this on multiple subs but get the same result.

**Comment by gottogogottogorightnow** [comment]
I have the same issue. It gets to 1% downloading on the first model on the list and just freezes. I left it going over night and no progress.

**Comment by DIGITALCRIMINAL** [comment]
What's your filename format?

**Comment by Gixxa** [comment]
Works fine for me my filename format is:

{post_id}-{date}-{filename}.{ext}

**Comment by Daironman78** [comment]
This is what it shows in config

    "onlyfans": {
      "settings": {
        "auto_profile_choice": [],
        "auto_model_choice": false,
        "auto_media_choice": "",
        "auto_api_choice": true,
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape_names": true,
          "scrape_paid_content": true
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}\\{username}\\{api_type}\\{value}\\{media_type}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}\\{username}\\Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklist_name": "",
        "webhook": true
      }

**Comment by Daironman78** [comment]
For the heck of it I changed the filename format in configuration to : {post_id}-{date}-{filename}.{ext} to match what Gixxa said but still no luck.  It gets to this point and just sits here : 

Processing metadata.
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Renaming files.
Scrape Completed

Download Processing
Name:  xxxxxxxl | Type: Posts | Count: 899 | Directory: C:\Users\Tony_\Downloads\OnlyFans-7.3\.sites

  0%|←[32m                                                                                                                                   ←[0m| 4.10k/2.20G [00:00<51:34:05, 1  0%|←[32m                                                                                                                                        ←[0m| 331k/2.20G [00:00<38:01,   0%|←[32m                                                                                                                                       ←[0m| 527k/2.20G [00:00<29:15, 1  0%|←[32m                                                                                                                                       ←[0m| 949k/2.20G [00:00<18:37, 1  0%|←[32m                                                                                                                                      ←[0m| 1.46M/2.20G [00:00<14:18, 2  0%|←[32m                                                                                                                                      ←[0m| 1.82M/2.20G [00:00<13:15, 2  0%|←[32m▏                                                                                                                                     ←[0m| 2.12M/2.20G [00:01<17:34, 2  0%|←[32m▏                                                                                                                                     ←[0m| 2.73M/2.20G [00:01<13:17, 2  0%|←[32m▏                                                                                                                                     ←[0m| 3.72M/2.20G [00:01<08:33, 4  0%|←[32m▎                                                                                                                                     ←[0m| 4.22M/2.20G [00:01<09:13, 3  0%|←[32m▎                                                                                                                                     ←[0m| 4.77M/2.20G [00:01<09:00, 4  0%|←[32m▎                                                                                                                                     ←[0m| 5.21M/2.20G [00:01<08:57, 4  0%|←[32m▎                                                                                                                                     ←[0m| 5.33M/2.20G [00:15<08:57, 4.08MB/s]←[0m

**Comment by Daironman78** [comment]
Any suggestions from anyone on this. Still having the same issue where its just showing Download Processing but nothing is happening. I cant figure this out at all.

**Comment by DIGITALCRIMINAL** [comment]
Has this been fixed with the latest update?

**Comment by Daironman78** [comment]
> 
> 
> Has this been fixed with the latest update?

No luck. I have downloaded the latest update but am still having the same issue with the download not moving. 
![Capture](https://user-images.githubusercontent.com/81696044/122647001-bc4b3400-d0e7-11eb-88bf-f9f3ed55d4d5.PNG)

**Comment by Gixxa** [comment]
This has happend to me too with the latest master. Just wait for it it will continue. I can't say how long it took for me as I was watching F1 qualifying but it was done after Q1 so a max of 20 minutes. 

I'll try the latest master c60cf89 in just a second and see what it will do.

**Comment by Daironman78** [comment]
Yes I downloaded the latest requirements and still had this issue a few hours ago and have been trying to play with it ever since.  On the last update I tried to scrape and left it running for over 24 hours just to see what would happen and no movement after the same spot as above.

**Comment by Daironman78** [comment]
Has anyone come up with any other suggestions for me on this yet? I removed the latest version and re-downloaded and am still getting the same results with the downloads being stuck at 0%.

**Comment by Daironman78** [comment]
Nevermind. Good news, I figured it out thanks to Gixxa. After downloading the latest scraper again, I noticed that the pysocks requirement was not installed. I installed that requirement and everything is working fine now.  Thanks for the help you guys.

**Comment by DIGITALCRIMINAL** [comment]
> Nevermind. Good news, I figured it out thanks to Gixxa. After downloading the latest scraper again, I noticed that the pysocks requirement was not installed. I installed that requirement and everything is working fine now. Thanks for the help you guys.

Did you have socks5 active?
