### ISSUE TITLE
archived content error: no ip

### ISSUE THREAD

**Issue by James-MF-Thomas** [DIGITALCRIMINAL/OnlyFans#492]
![Screen Shot 2020-11-08 at 7 41 57 AM](https://user-images.githubusercontent.com/47627618/98466571-f6d61100-2195-11eb-8688-5e4675a4fe62.png)

**Comment by DIGITALCRIMINAL** [comment]
Should be fixed now

**Comment by valdearg** [comment]
```
2020-11-08 14:46:34,093 ERROR errors 'list' object has no attribute 'ip'
Traceback (most recent call last):
  File "G:\Scripts\OnlyFans\datascraper\main_datascraper.py", line 85, in start_datascraper
    sessions = api_helper.create_session(settings=json_settings)
  File "G:\Scripts\OnlyFans\apis\api_helper.py", line 115, in create_session
    setattr(session, "ip", "")
AttributeError: 'list' object has no attribute 'ip'
```
Is this the same issue? Just pulled the latest version.

**Comment by DIGITALCRIMINAL** [comment]
Pushed another commit, it will fix the issue.

**Comment by valdearg** [comment]
Cheers man, that's got it!

**Comment by James-MF-Thomas** [comment]
getting the error again only under with messages this time:
![Screen Shot 2020-11-08 at 9 03 10 AM](https://user-images.githubusercontent.com/47627618/98468692-440bb000-21a1-11eb-86d1-e71a838d9842.png)

**Comment by valdearg** [comment]
Do another git pull, should be all set.

**Comment by James-MF-Thomas** [comment]
lol fuck i wish
![Screen Shot 2020-11-08 at 9 19 31 AM](https://user-images.githubusercontent.com/47627618/98469164-99e15780-21a3-11eb-8072-9aa004bef2b3.png)

**Comment by DIGITALCRIMINAL** [comment]
yikes, delete that metadata

**Comment by James-MF-Thomas** [comment]
somehow my username is the list

thats what i believe
![Screen Shot 2020-11-08 at 10 30 46 AM](https://user-images.githubusercontent.com/47627618/98470782-b1254280-21ad-11eb-8384-7ef46141c934.png)
 is causing the traceback

**Comment by James-MF-Thomas** [comment]
did a clean install, works for model by model but not for scrape_all_names nor my username

**Comment by DIGITALCRIMINAL** [comment]
Thanks, the problem should be fixed in the latest commit

**Comment by DIGITALCRIMINAL** [comment]
Btw it was because your account is a creator account and I forgot to add the IP attribute to non proxied sessions.

**Comment by James-MF-Thomas** [comment]
still getting this:
![Screen Shot 2020-11-08 at 7 38 31 PM](https://user-images.githubusercontent.com/47627618/98491449-772e5d80-21fa-11eb-903e-231683751a73.png)

**Comment by DIGITALCRIMINAL** [comment]
@James-MF-Thomas does it work if you do your username on its own?

**Comment by James-MF-Thomas** [comment]
It does not

**Comment by James-MF-Thomas** [comment]
It did in the past, previous to the update. But not now.

**Comment by James-MF-Thomas** [comment]
if I could blacklist myself i would.

**Comment by DIGITALCRIMINAL** [comment]
Try the latest commit and let me see the error

**Comment by James-MF-Thomas** [comment]
![Uploading Screen Shot 2020-11-09 at 1.46.33 AM.png…]()

**Comment by DIGITALCRIMINAL** [comment]
image is not working @James-MF-Thomas

**Comment by James-MF-Thomas** [comment]
![Screen Shot 2020-11-09 at 1 46 33 AM](https://user-images.githubusercontent.com/47627618/98513582-b4601300-222d-11eb-8bc7-611826221e63.png)

**Comment by DIGITALCRIMINAL** [comment]
As I thought lol... you're not downloading the latest commit; instead, you keep downloading the latest release.

**Comment by James-MF-Thomas** [comment]
Fuck me.. my bad.  I gotcha

**Comment by DIGITALCRIMINAL** [comment]
It works right?

**Comment by James-MF-Thomas** [comment]
Like a pool

**Comment by James-MF-Thomas** [comment]
thanks again for all your hard brother. if i didn't know any better i'd say you're a good dude 🍻
