### ISSUE TITLE
Only grabbing 1 out of multiple images in an image "set"

### ISSUE THREAD

**Issue by bobsage123** [DIGITALCRIMINAL/OnlyFans#89]
I noticed for image "sets" aka where you can click the right arrow on an image to see more similar images from that set, it is only scrapping 1 out of however many there is.

I think it may be because of my below naming scheme. Since they are all part of the same set, they have the same "text". 

I also noticed that if several images are posted in one day, but have no text, it will only download one of them. Since the file name will be the same thing.

I'm assuming all of this applies to videos too.

Is there a way that an incremental number could be added to these set images so all of them download?

[{date}] {text}.{ext}

Edit: Also want to note I have the "Don't redownload a file if the file name exists exists" option checked since I don't want to have to redownload everything everytime. Maybe I'm confusing this option and it doesn't actually redl everything but turning it on would fix the above issue?

**Comment by DIGITALCRIMINAL** [comment]
Better to just use this {date}/{text}-{file_name}.{ext} as a name format so it doesn't overwrite the same file

**Comment by bobsage123** [comment]
Thanks. I ended up adding all three to the filename itself. Put file_name at the end so there were no duplicates.

For text_length, does the limit I put account for just the text, or the entire file name? Reason I ask is because I set it to 120 and the text portion went over 200 characters (with spaces).

**Comment by DIGITALCRIMINAL** [comment]
Gonna have to fix that when I have time .-.

**Comment by deyan-mladenov** [comment]
I am here to say that I appreciate your work.

**Comment by bobsage123** [comment]
> Gonna have to fix that when I have time .-.

Ok TY

**Comment by DIGITALCRIMINAL** [comment]
I updated the script. Don't know if it's been fixed.

**Comment by bobsage123** [comment]
Hello, the issue with setting "text length" (which I believe just refers to the text description of a post, and does not include the date, etc) still does not seem to be working.
I've been using the below format for naming, so I get some of the description in the file name. This runs into issues when there is multiple images with the same text in a post, and the length exceeds the windows filename limit. There is no space left to add ({file_name}) to the end, so it only ends up downloading 1 out of the multiple images in the set. Since the rest are seen as duplicates.
[{date}] {text} ({file_name}).{ext}

I'd like to set a limit on the text description size, so that there will always be enough room for the ({file_name}) if possible.

**Comment by DIGITALCRIMINAL** [comment]
I had to disable the text format because there are so many problems with it.

You can uncomment line 42 in modules/helpers.py to active the text format
![image](https://user-images.githubusercontent.com/21285176/74075915-02c95280-4a0d-11ea-8806-46f385e25e89.png)

**Comment by bobsage123** [comment]
I'm actually on version 3.6.1 before this was removed. I am trying to add file name second, maybe that will resolve the issue (unless the file name on OF is exceptionally long).

**Comment by bobsage123** [comment]
Unfortunantly same issues, You're right so many issues with text. If there was some simple way to just lessen the character limit of text, that would fix some issues. Then there's just a few other things like emojis' etc that may cause problems

**Comment by fungastorba** [comment]
What about the 'text_length' config option? Mine is set to 50, and I don't have problems.

**Comment by DIGITALCRIMINAL** [comment]
> I'm actually on version 3.6.1 before this was removed. I am trying to add file name second, and text third. Maybe that will resolve the issue (unless the file name on OF is exceptionally long). Only annoying part is having to re-dl everything. Not sure if it will auto-rename instead of re-dl if it sees the same file named something else.

Even if I tried to fix the text format, there's a good chance it will redownload all the stuff again in the same folder. It's best to just do it without text.

**Comment by bobsage123** [comment]
Ahhh. I wonder if there's some easy way to use a tiny script after the fact to insert a certain amount of characters from the text into the file name from the metadata files.

**Comment by fungastorba** [comment]
I have never programmed in Python, otherwise I would love to take a crack at it myself. But in theory bobsage's suggestion is in my opinion the way it must be working right now (or before he disabled it).   The problems that Mr Criminal described stand either way.

**Comment by bobsage123** [comment]
> I have never programmed in Python, otherwise I would love to take a crack at it myself. But in theory bobsage's suggestion is in my opinion the way it must be working right now (or before he disabled it). The problems that Mr Criminal described stand either way.

Now that I think of it, that's probably true. It seems a list of all the "odd" characters in the text like random slashes, emojis, would need to be ignored and parsed out. But I'm not a programer either so no idea if it's that simple. Plus like digital mentioned, there's different file name length limits per OS, etc.

**Comment by DIGITALCRIMINAL** [comment]
> > I have never programmed in Python, otherwise I would love to take a crack at it myself. But in theory bobsage's suggestion is in my opinion the way it must be working right now (or before he disabled it). The problems that Mr Criminal described stand either way.
> 
> Now that I think of it, that's probably true. It seems a list of all the "odd" characters in the text like random slashes, emojis, would need to be ignored and parsed out. But I'm not a programer either so no idea if it's that simple. Plus like digital mentioned, there's different file name length limits per OS, etc.
> 
> @DIGITALCRIMINAL My friend from another forum used to have a working python script, that actually did manage to parse the texts correctly, and worked on all OS'. He hasn't updated the script in a while so overall it doesn't work, but that portion may still be valid. I could send over the code if you're interested.

Yeah, please send the link or code please

**Comment by bobsage123** [comment]
Here you go - 

`import requests
import json
from bs4 import BeautifulSoup
from urllib.parse import urljoin
import re
import logging
from pathlib import Path
import os, sys
from concurrent.futures import ThreadPoolExecutor, as_completed
import argparse
import urllib3
from zipfile import ZipFile, ZIP_DEFLATED

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)


parser = argparse.ArgumentParser(description='Onlyfans scraper')
parser.add_argument('--email', help="Email of the account to log into", required=True)
parser.add_argument('--password', help="Password of the account to log into", required=True)
parser.add_argument('--recheck-size', help='Checks source data headers against files. If a size mismatch'
                                          ' is detected, it downloads the file again. Useful if you suspect some files'
                                          ' have been corrupted by cancel/network outage...', action='store_true')
parser.add_argument("--target-dir", help="Target directory for downloads. This folder by default.", default=".")
parser.add_argument("--user-agent", help="Set a custom user agent. Required when using log in from cookie.",
                   default="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36")
parser.add_argument("--workers", help="Number of workers while downloading posts on a page", default=3, type=int)
parser.add_argument("--offset", help="Resume from that point on", default=0, type=int)

args = parser.parse_args()

EMAIL = args.email
BASE_URL = "https://onlyfans.com/"
POSTS_URL = "https://onlyfans.com/api2/v2/posts"
SAFE_PTN = '[^0-9a-zA-Z-_.()]+'
NUM_WORKERS = args.workers
FORCE_CONTINUE = True
target_dir = Path(args.target_dir)
RECHECK_SIZE = args.recheck_size
SKIP = False
offset = args.offset
limit = 10

logger = logging.getLogger("onlyfans")
logger.setLevel(logging.INFO)
ch = logging.StreamHandler()
ch.setLevel(logging.INFO)

fh = logging.FileHandler("onlyfans.log")
formatter = logging.Formatter('%(asctime)s - ' + (EMAIL or "No email") + ' - %(levelname)s - %(message)s')
fh.setFormatter(formatter)
fh.setLevel(logging.WARN)

logger.addHandler(ch)
logger.addHandler(fh)

zipname = "log-data.zip"
if os.path.exists(zipname): os.remove(zipname)
z = ZipFile(zipname, "w", ZIP_DEFLATED)

def download(params):
   url, folder, filename, fileid = params
   folder = target_dir/folder
   folder.mkdir(parents=True, exist_ok=True)
   tmpfilepath = folder/("." + filename)
   filepath = folder/filename
   if not url:
       return False
   for i in range(3):
       origfilename = Path(url.split("/")[-1])

       if RECHECK_SIZE:
           r = s.head(url)
           sizematch = filepath.exists() and filepath.stat().st_size == int(r.headers.get('Content-Length', '0'))
       else:
           sizematch = True  #Assumed

       if filepath.exists() and sizematch:
           logger.info("Skipped {}".format(filepath))
           return False
       if origfilename.exists():
           logger.info("Found {}. Renaming to {}".format(origfilename, filepath))
           origfilename.replace(filepath)
           return True

       if fileid:
           dupes = list(folder.glob("{}_*".format(fileid)))
           if dupes:
               dupes[-1].rename(filepath)
               logger.info("Renaming {} into {}".format(str(dupes[-1]), filename))
               for dupe in dupes[:-1]:
                   dupe.unlink()
                   logger.info("Deleting duplicate {}".format(str(dupe)))
               return False

       if SKIP:
           return True

       r = s.get(url, stream=True, verify=False)
       content_length = int(r.headers.get('Content-Length', '0'))
       logger.info("Downloading {} ({:.2f}MB)".format(filepath, content_length / 1048576))
       size = 0
       try:
           with tmpfilepath.open('wb+') as f:
               for chunk in r.iter_content(chunk_size=1024*512):
                   if chunk:  # filter out keep-alive new chunks
                       size += f.write(chunk)
       except:
           if filepath.exists():
               filepath.unlink()
       if content_length and size != content_length:
           filepath.unlink()
           logger.warning("Downloading {} failed, retrying...".format(filepath))
       else:
           tmpfilepath.rename(filepath)
           return True
   raise Exception("Failed 3 times: {} should be {} bytes but got {} bytes instead".format(
       filepath, content_length, size))

def get_token(session):
   r = s.get("https://onlyfans.com")
   b = BeautifulSoup(r.text, "lxml")
   try:
       r = s.get(urljoin(r.url, b.select_one("link[href*='js/app']")['href']))
       app_token = re.search('o="([a-f0-9]{32})"', r.text).group(1)
       if not app_token:
           logger.error("Error while retrieving the app-token")
           raise Exception("Error while retrieving the app-token")
       logger.info("Successfully retrieved app-token: %s" % app_token)
   except:
       logger.exception("Could not retrieve the app-token")

   return app_token

s = requests.Session()

s.headers.update({
   'origin': 'https://onlyfans.com',
   'referer': 'https://onlyfans.com/',
   'user-agent': args.user_agent
})

cookiepath = Path('cookie_%s.json' % EMAIL)
logged_in = False
if cookiepath.exists():
   with cookiepath.open() as f:
       try:
           cookie = {x['name']:x['value'] for x in json.load(f)}
           s.cookies.update(cookie)
           r = s.get("https://onlyfans.com/my/banking")
           if "href='/logout'" in r.text:
               logged_in = True
           app_token = get_token(s)
       except Exception as exc:
           logger.exception("Something went wrong while loading the cookie.")
else:
   with cookiepath.open("w+") as f:
       json.dump([],f)

if not logged_in:


   data = {
       'email': EMAIL,
       'password': args.password or input("password: "),
       'js': '1'
       }
   r = s.post('https://onlyfans.com/component/login/post/login', data=data)

   s.headers.pop('origin')
   s.headers['referer'] = "https://onlyfans.com"
   r = s.get("https://onlyfans.com")

   if "spa/js/app" in r.text:
       logged_in = True
       with cookiepath.open('w+') as f:
           json.dump([{'name': k, 'value': v} for k, v in s.cookies.get_dict().items()], f)
       logger.info("Successful login")
       app_token = get_token(s)
   else:
       with open("home.html", "w+") as fhome:
           fhome.write(r.text)
       logger.error("Impossible to Log In.")
       input("There are many possible reasons for this error\n"
             "1) Check that the username & password are correct\n"
             "2) Onlyfans requested a captcha => install an extension for cookie management\n"
             "   like EditThisCookie and export your browser cookie to this folder, under the filename\n"
             "   cookie_{email}.json (should already be existing). Then look up your user-agent of your\n"
             "   browser: (press F12 in chrome, go to the 'Network' tab, click a link on onlyfans and copy the\n"
             "   value associated with 'user-agent' in the headers of the request). Then use pass it as an option\n"
             "   like so: --user-agent \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
             "(KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36\"\n"
             "Press enter to close this window.".format(email=EMAIL))
       raise Exception("Log in failed.")


while True:
   download_list = []
   logger.info("Retrieving posts limit {limit} - offset {offset}".format(limit=limit,offset=offset))
   r = s.get(POSTS_URL, params={'limit': limit,'offset': offset,'app-token':app_token})
   z.writestr("{}.json".format(offset), r.text)
   j = r.json()
   if len(j) == 0:
       logger.info("Reached end of feed: latest call at limit {limit} - offset {offset} returned {lenj} items".format(
           limit=limit, offset=offset, lenj=len(j)
       ))
       break

   for item in j:
       try:
           post_title = BeautifulSoup(item['text'], "lxml").text
           post_title_text = re.sub(SAFE_PTN, ' ',  post_title.strip() or 'No description').strip().replace(' ', '_')
           post_id = str(item['id'])
           user = item['author']['username']
           publish_date = item['postedAt'][:10]
           for i, media in enumerate(item['media']):
               url = media.get('full', media.get('source',{}).get('source', media['info']['source']['source']))
               hash, ext = os.path.splitext(url.split("/")[-1])
               fileid = "_".join([publish_date, post_id, str(i+1)])
               filename = "{}_{}{}".format(fileid, post_title_text[:100], ext)
               download_list.append((url,Path(user),filename,fileid))
       except:
           if not os.path.exists("error"): os.mkdir("error")
           error_filename = "error/{}.json".format(item['id'])
           logger.info("Cannot parse item {} - dumping it to {}".format(item['id'],error_filename))
           with open(error_filename, 'w+') as f:
               json.dump(item, f)

   should_continue = False
   try:
       with ThreadPoolExecutor(max_workers=NUM_WORKERS) as executor:
           for future in as_completed([executor.submit(download, item) for item in download_list]):
               if future.result():
                   should_continue = True
   except KeyboardInterrupt:
       logger.info("Stopping scraping")
       z.close()
       break
   if should_continue or FORCE_CONTINUE:
       offset += limit
   else:
       break
`

**Comment by bobsage123** [comment]
Just saw the latest release. Were you able to fix the text length limit setting issue?

**Comment by DIGITALCRIMINAL** [comment]
New naming format

**Comment by DIGITALCRIMINAL** [comment]
> Just saw the latest release. Were you able to fix the text length limit setting issue? Also, will it rename a file instead of redownloading if you now use a new naming format?

New naming format. It's the same as the code above. I believe I have fixed the text length limit.
